language: java
install: true

os: linux
dist: trusty
jdk: openjdk11

sudo: required
services: docker

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then ./gradlew clean test; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker build -t xicks/fibonacci-server . ; fi'

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -fr $HOME/.gradle/caches/*/scripts/
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"