version: '3'
services:
  redis:
    image: 'redis:latest'
    expose:
      - "6379"
    ports:
      - "6379:6379"
  postgres:
    image: "postgres"
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: "admin"
  fibonacci-server:
    build: .
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    depends_on:
      - postgres
      - redis


